### ISSUE TITLE
Ability to add custom Thumbor filters at runtime (via ENV or volume mount)?

### ISSUE THREAD

**Issue by mohavee** [beeyev/thumbor-s3-docker#39]
### Context

I’m using the `beeyev/thumbor-s3-docker` image and would like to add my own Thumbor filters (e.g. a `rotate_any` filter) without forking or rebuilding the image every time.

### Questions

1. **Is there an existing mechanism** in the current design to load additional filter modules at runtime?  
   - For example, mounting a directory of `.py` filter files and pointing Thumbor’s `FILTERS_PATH` to it via an environment variable or config option.
2. **If not**, what would you recommend as the simplest way to extend the image with custom filters?  

Thanks for any pointers!

**Comment by beeyev** [comment]
Could you please provide me an example how you would like it to work?

**Comment by mohavee** [comment]
Here is example of thumbor filters at runtime—no image rebuild required.

### 1. Add filter modules

Create a directory in project (e.g. `custom_filters/`) and place filter `.py` files there:

```bash
mkdir -p custom_filters
cat > custom_filters/rotate_any.py << 'EOF'
from thumbor.filters import BaseFilter, filter_method
from PIL import Image

class Filter(BaseFilter):
    @filter_method(BaseFilter.Number)
    def rotate_any(self, angle):
        img = self.engine.image.convert("RGBA")
        rotated = img.rotate(angle, expand=True)
        white_bg = Image.new("RGBA", rotated.size, (255,255,255,255))
        combined = Image.alpha_composite(white_bg, rotated).convert("RGB")
        self.engine.image = combined
EOF
````

### 2. Create a Jinja2 template for `thumbor.conf`

Save this as `thumbor.conf.tpl` and mount it into `/etc/thumbor/thumbor.conf.tpl`:

```jinja
## … existing Thumbor config … ##

{% raw %}
{% set default_filters = [
    'thumbor.filters.brightness',
    'thumbor.filters.colorize',
    /* … other built-ins … */
    'thumbor.filters.stretch'
] %}

{# Merge in any custom module names #}
{% if CUSTOM_FILTER_MODULES is defined %}
  {% set filters = default_filters + CUSTOM_FILTER_MODULES.split(',') %}
{% else %}
  {% set filters = default_filters %}
{% endif %}

FILTERS = {{ filters }}

{# Append custom directories to FILTERS_PATH #}
{% if CUSTOM_FILTER_PATHS is defined %}
  {% for path in CUSTOM_FILTER_PATHS.split(',') %}
FILTERS_PATH.append('{{ path }}')
  {% endfor %}
{% endif %}
{% endraw %}
```

### 3. Configure Docker (e.g. `docker-compose.yml`)

```yaml
version: '3.8'
services:
  thumbor:
    image: beeyev/thumbor-s3-docker:latest
    volumes:
      - ./custom_filters:/app/custom_filters:ro
      - ./thumbor.conf.tpl:/etc/thumbor/thumbor.conf.tpl:ro
    environment:
      # Comma-separated module paths to include in FILTERS
      CUSTOM_FILTER_MODULES: "custom_filters.rotate_any"
      # Comma-separated directories to append to FILTERS_PATH
      CUSTOM_FILTER_PATHS: "/app/custom_filters"
```

#### Environment variables

* **CUSTOM\_FILTER\_MODULES**
  A comma-separated list of Python module paths (no spaces), e.g.
  `custom_filters.rotate_any,custom_filters.foo_bar`

* **CUSTOM\_FILTER\_PATHS**
  A comma-separated list of directories to append to Thumbor’s `FILTERS_PATH`, e.g.
  `/app/custom_filters,/mnt/extra_filters`

### 4. Test filter

Request filter via the Thumbor URL API:

```
http://localhost:8888/unsafe/filters:rotate_any(45)/https://…/image.png
```


If you think this feature would be useful in the image, I’d create a PR. Or do you have better/more straightforward approach?
